### ISSUE TITLE
Desarrollar vista de historial médico en perfil del usuario

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#115]
Como usuario, quiero ver el historial médico de las mascotas que he adoptado y poder incluir nuevos registros de datos en el historial

![image](https://user-images.githubusercontent.com/3885211/187495129-5f70a018-b449-487b-9aaa-b64aa9f58c62.png)

- [ ] Desarrollar vista en tab de perfil y componentes para listar mascotas adoptadas por el usuario
- [ ] Al seleccionar una mascota, mostrar en el componente de la derecha los detalles relacionados a su historial médico (ver cómo lo estructurará el backend para crear y usar mock data)
- [ ] Añadir enlace a la conversación con el centro de adopción
- [ ] Crear o reutilizar componente de modal para poder registrar nueva entrada médica
- [ ] De no estar disponible el back, trabajar con mock data y desarrollar la lógica de todo el proceso
- [ ] Pruebas funcionales

**Comment by SebastianRamirezB** [comment]
@pedrovelasquez9 hola, creo que esta issue está duplicada o es parecida a la issue #100

**Comment by pedrovelasquez9** [comment]
@SebastianRamirezB en efecto, está duplicada, la cierro para quedarnos con la 100, muchas gracias por avisarme!

**Comment by pedrovelasquez9** [comment]
Duplicated issue
