### ISSUE TITLE
Maquetar layout de web

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#13]
Como usuario, al entrar en la plataforma, debo poder ver y navegar a través de la estructura básica de la web 

Referencia de diseño: https://www.figma.com/file/vPbv7juJYXXr5Hb8UNIcHF/Landing?node-id=74%3A1127 

- [x] Crear sistema base de rutas
- [x] Maquetar nav y footer
- [x] Agregar funcionalidad y estilo responsive al nav

**Comment by victormolla14** [comment]
Buenas @GreZu28 ! Cómo llevas esta tarea? 😁

**Comment by GreZu28** [comment]
Hola! La he completado, estoy esperando a que se apruebe el pull request para cerrarla.
