### ISSUE TITLE
Maquetar sección "tu nuevo compañero de vida" en el home

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#15]
Como usuario, quiero ver la sección "tu nuevo compañero de vida" al hacer scroll en el home

Referencia de diseño: https://www.figma.com/file/vPbv7juJYXXr5Hb8UNIcHF/Landing?node-id=74%3A1127

- [x] Dividir sección en componentes reutilizables para listado de mascotas 
- [x] Crear mock data para el listado a mostrar
- [x] Desarrollar e implementar componentes y sección de página
- [x] Aplicar responsive design

**Comment by victormolla14** [comment]
Buenas @luismvl ! Cómo llevas esta tarea? 😁

**Comment by roqueheli** [comment]
Hola @victormolla14 conversé con @pedrovelasquez9 al respecto de esta tarea y acordamos que me la asignara ya que tiene mucho tiempo creada y no tiene avance.
