### ISSUE TITLE
Revisar modelo BD

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#2]
Como desarrollador, quiero revisar el modelo inicial de la base de datos para identificar potenciales cambios y entender las relaciones entre las entidades propuestas

- [x] Revisar modelo de BD
- [x] Modificar modelo de BD si se ha detectado la necesidad

**Comment by magg77** [comment]
Podemos ver como quedo la bd, se al final realizaron cambios? Muchas gracias

**Comment by pedrovelasquez9** [comment]
> Podemos ver como quedo la bd, se al final realizaron cambios? Muchas gracias

Si, tienen el modelo actualizado en el Notion: https://www.notion.so/OpenDevs-fe43378c12214f819adab53f2e358071
