### ISSUE TITLE
Crear CRUD de mascotas

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#24]
Como desarrollador, quiero tener en la API de backend las operaciones necesarias para poder registrar, editar, eliminar y consultar mascotas asociadas a un centro de una protectora

- [x] Crear modelo de mascotas
- [x] Crear ruta de mascotas para el CRUD
- [x] Crear controlador con operaciones CRUD usando el modelo creado
- [x] Aplicar validaciones y casos de error
- [x] Probar endpoints

**Comment by victormolla14** [comment]
Buenas @KussFrSo ! Cómo llevas esta tarea? 😁

**Comment by KussFrSo** [comment]
Acabo justo de empezar 😆, que he estado el finde de vacaciones y ayer me volví a organizar con camper

**Comment by KussFrSo** [comment]
Me falta acabar de revisar el código y acabar de concretar un par de cosas con mis compañeros de backend
