### ISSUE TITLE
Desarrollar CRUD de protectoras y centros

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#26]
Como desarrollador, quiero tener en la API de backend las operaciones necesarias para poder registrar, editar, eliminar y consultar protectoras y centros asociados a las protectoras

- [x]  Crear modelo de protectoras y centros (tomar en cuenta las relaciones)
- [x]  Crear ruta de protectoras y centros para el CRUD
- [x]  Crear controladores con operaciones CRUD usando los modelos creados
- [x]  Aplicar validaciones y casos de error a ambos controladores
- [x]  Probar endpoints

**Comment by Ezequiel-Manfredi** [comment]
> 

creo que la segunda tarea dice ruta mascotas pero debería ser protectoras

**Comment by pedrovelasquez9** [comment]
> > 
> 
> creo que la segunda tarea dice ruta mascotas pero debería ser protectoras

Correcto, actualizada
