### ISSUE TITLE
Crear CRUD y métodos de autenticación

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#28]
Como desarrollador, necesito tener operaciones en la API para registrar, editar, eliminar y obtener data de un usuario, además, proporcionarle opciones como recuperar su contraseña y permitirle hacer consultas u operaciones de acuerdo a su nivel o estado de autenticación en la plataforma

- [x] Crear modelo de usuarios (tomar en cuenta las relaciones)
- [x]  Crear ruta de usuarios para el CRUD
- [x] Crear ruta de usuarios para recuperar contraseña y renovar token de acceso
- [x]  Crear controladores con operaciones CRUD usando los modelos creados
- [x] Crear middlewares necesarios para verificar autenticación y dar acceso a consultar otros endpoints restringidos de la API
- [x]  Aplicar validaciones y casos de error 
- [x]  Probar endpoints

**Comment by pedrovelasquez9** [comment]
@Ezequiel-Manfredi puedo dar la tarea por cerrada o falta algún matiz?

**Comment by Ezequiel-Manfredi** [comment]
@pedrovelasquez9 estoy esperando al merge de la PR para poder cerrarla

**Comment by pedrovelasquez9** [comment]
> @pedrovelasquez9 estoy esperando al merge de la PR para poder cerrarla

Listo el merge =)
