### ISSUE TITLE
Maquetar vista de búsqueda de mascota

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#40]
Como usuario, quiero buscar a mi mascota ideal aplicando filtros según las características que considere idóneas

Referencia de diseño: https://www.figma.com/file/vPbv7juJYXXr5Hb8UNIcHF/Landing?node-id=74%3A1127

- [x]  Crear ruta y página de búsqueda de mascotas
- [x]  Descargar/solicitar recursos de diseño
- [x]  Crear componente con formulario y handler de filtros disponibles
- [x]  Crear componente con ficha de mascotas para mostrar resultados acorde a filtros aplicados
- [x]  Crear handlers para paginación por peticiones al backend 
- [x]  Aplicar responsive design

**Comment by victormolla14** [comment]
Buenas @roqueheli ! Cómo llevas esta tarea? 😁

**Comment by roqueheli** [comment]
Hola @victormolla14 , estoy avanzando. Sólo no había marcado las tareas que ya llevo listas, espero entre hoy y mañana tener todo listo.

**Comment by roqueheli** [comment]
@victormolla14 @pedrovelasquez9 @AMDevelopOB tarea lista, generé el pull request para la rama develop. Saludos
