### ISSUE TITLE
Maquetar vista de detalle de mascota

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#41]
Como usuario, al seleccionar una mascota, me gustaría ver su ficha de detalles para saber más sobre sus características y comportamiento

![image](https://user-images.githubusercontent.com/3885211/186191257-80346d31-ced6-49d2-97eb-67ac382e0164.png)

Referencia de diseño: https://www.figma.com/file/vPbv7juJYXXr5Hb8UNIcHF/Landing?node-id=74%3A1127

- [x]  Crear ruta dinámica para cargar ficha de mascota seleccionada por id
- [x]  Descargar/solicitar recursos de diseño
- [x]  Crear componentes y página para mostrar ficha de detalle tras recibir información del backend
- [x]  Crear componente para mostrar modal de inicio de sesión en caso de que no haya sesión iniciada y el usuario quiera adoptar 
- [x]  Aplicar responsive design

**Comment by victormolla14** [comment]
Buenas @SebastianRamirezB ! Cómo llevas esta tarea? 😁

**Comment by SebastianRamirezB** [comment]
Hola Víctor, ayer me la asigné, ya estoy trabajando en ella.

**Comment by diloes** [comment]
¿ Cómo vas con esto @SebastianRamirezB  ?

**Comment by SebastianRamirezB** [comment]
Hola, me falta terminar de aplicar el responsive desing y el modal, espero realizar la pull request en la noche :)
