### ISSUE TITLE
Maquetar buscador de protectoras

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#42]
Como usuario, quiero poder ubicar centros de protectoras cerca de mi ubicación para poder visitarlos y ver las mascotas que tienen en el centro seleccionado 

![image](https://user-images.githubusercontent.com/3885211/186191660-af7cd6c6-33c6-4f0c-bf56-d590d65c0506.png)

Referencia de diseño: https://www.figma.com/file/vPbv7juJYXXr5Hb8UNIcHF/Landing?node-id=74%3A1127

- [x]  Crear ruta y página de búsqueda de centros de protectoras
- [x]  Descargar/solicitar recursos de diseño
- [x]  Crear componente con formulario y handler de filtros disponibles
- [x]  Crear componente con ficha de centros para mostrar en el listado de resultados 
- [x] Crear componente de mapa para buscar y ubicar centros por sus coordenadas de forma visual
- [x]  Aplicar responsive design

**Comment by victormolla14** [comment]
Buenas @Ceskkk ! Cómo llevas esta tarea? 😁

**Comment by Ceskkk** [comment]
Buenas @victormolla14 la empecé ayer mismo, en proceso lo tengo!

**Comment by diloes** [comment]
¿ Cómo vas con el mapa @Ceskkk ?
