### ISSUE TITLE
Maquetar página de detalles de centro

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#43]
Como usuario, quiero poder ver más detalles del centro seleccionado consultando datos base del centro y listado de mascotas disponibles en él

![image](https://user-images.githubusercontent.com/3885211/186192141-128819b7-38a6-4753-83c8-192833a49bbb.png)

Referencia de diseño: https://www.figma.com/file/vPbv7juJYXXr5Hb8UNIcHF/Landing?node-id=74%3A1127

- [x]  Crear ruta dinámica para ver detalles del centro por id tras obtener datos del backend
- [x]  Descargar/solicitar recursos de diseño
- [x]  Crear componentes y página para mostrar datos del centro
- [x]  Aplicar responsive design
- [x] Agregar componente de listado de mascotas con mascotas asociadas al centro en cuestión
- [x] Crear componente de modal (o reutilizar si ya se tiene uno) para validar si el usuario ha iniciado sesión en caso de querer contactar con el centro a través de un mensaje directo
- [x]  Crear handlers para paginación por peticiones al backend

**Comment by victormolla14** [comment]
Buenas @Yauris12 ! Cómo llevas esta tarea? 😁

**Comment by Yauris12** [comment]
Hola Victor ayer , recien me la asigne , hoy empiezo a avanzar esta tarea

**Comment by diloes** [comment]
¿ Qué tal vas @Yauris12  ?
