### ISSUE TITLE
Implementar manejo de errores

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#61]
Como usuario, quiero que la API retorne errores coherentes para poder capturarlos de forma rápida en el frontend y redireccionar en función del error recibido

- [x] Definir errores, mensajes y casos de error 
- [x] Implementar middleware o estrategia de captura de errores 
- [x] Agregar errores a documentación de swagger
- [x] Probar endpoint y casos de error

**Comment by Ezequiel-Manfredi** [comment]
> Como usuario, quiero que la API retorne errores coherentes para poder capturarlos de forma rápida en el frontend y redireccionar en función del error recibido
> 
> * [ ]  Definir errores, mensajes y casos de error
> * [ ]  Implementar middleware o estrategia de captura de errores
> * [ ]  Agregar errores a documentación de swagger
> * [ ]  Probar endpoint y casos de error

Ya los hice en la PR #45 :
- los errores contemplados son:
  - 400: para parámetros erróneos
  - 404: para recursos no encontrados
- los mensajes son los por defecto del error lanzado por el `schema` de validación con un reporte personalizado
- la estrategia de captura es a través del `error handler`
- los errores ya están en los endpoints del swagger

Si pudieras echarle un vistazo para ver si es a lo que se refiere esta issue o esta incompleto lo implementado hasta ahora.
(con la salvedad de los endpoints aun no implementados)
