### ISSUE TITLE
Maquetar vista de reseñas de protectora

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#76]
Como usuario, al entrar al detalle de una protectora y seleccionar la opción "ver reseñas" quiero poder ver un listado de reseñas realizadas por otros usuarios de la plataforma

![image](https://user-images.githubusercontent.com/3885211/186199942-2bac8836-cc3c-4cee-ac6a-3b89aa6c4de0.png)

- [ ] Agregar ruta y página de reseñas
- [ ] Agregar enlace a reseñas desde página de detalles de centros
- [ ] Agregar detalles de centro (si no se tiene un servicio de back, usar data mock)
- [ ] Agregar listado de reseñas (si no se tiene un servicio de back, usar data mock)
- [ ] Agregar botón para volver a página anterior
- [ ] Agregar botón para enviar mensaje
- [ ] Agregar enlace para ver listado completo de mascotas en adopción
- [ ] Pruebas funcionales

**Comment by diloes** [comment]
¿ Qué tal vas @julenbero ?

**Comment by julenbero** [comment]
Estoy trabajando en ello, por temas de salud no habia podido adelantar estos dias

**Comment by diloes** [comment]
Ok @julenbero no hay problema.

**Comment by diloes** [comment]
Hola @julenbero ¿ Has podido avanzar ?

**Comment by julenbero** [comment]
Hola esta semana finalizo con la actividad, he tenido poco tiempo de dedicacion para ello
