### ISSUE TITLE
Maquetar página de ajustes de cuenta de usuario "mi cuenta"

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#77]
Como usuario, quiero poder editar la información de mi perfil dentro de la plataforma

![image](https://user-images.githubusercontent.com/3885211/186200627-9c78056c-9283-43b1-b8d2-3dd91de2dfbd.png)

- [x] Agregar ruta y página para entrar al perfil del usuario
- [x] Maquetar contenedor general con sistema de pestañas para acceder a las opciones disponibles según diseño
- [x] Agregar vista de opción "mi cuenta" 
- [x] Maquetar formulario y aplicar validaciones
- [x] Si no se tiene un servicio de back, usar data mock
- [x] Pruebas funcionales

**Comment by diloes** [comment]
¿ Cómo vas @GreZu28  ?

**Comment by GreZu28** [comment]
Hola @diloes!. Estoy avanzando, subiré lo que tengo lo más pronto que pueda, por si algún compañero necesita algo de lo que estoy haciendo.

**Comment by diloes** [comment]
Ok. Gracias !!

**Comment by diloes** [comment]
Hola @GreZu28 . ¿ Cómo vas con esas dos subtareas que te quedan ?

**Comment by GreZu28** [comment]
Hola @diloes, perdona por tardar en contestar, estaba terminando algunas cosas que quiero incluir en el pull request. Como mucho para mañana lo tengo. Un saludo!
