### ISSUE TITLE
Maquetar página de ajustes de cuenta de usuario, pestaña "mensajes"

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#78]
Como usuario, al entrar a mi cuenta y seleccionar la pestaña "mensajes" quiero poder ver un historial de conversaciones y, al seleccionar alguna, ver los mensajes que se han enviado y recibido

![image](https://user-images.githubusercontent.com/3885211/186201235-9921f7db-8bac-4b86-be8c-3a4a7dd38262.png)

- [x] Maquetar componente y anidar a contenedor de pestañas para visualizarlo al seleccionar la pestaña de mensajes
- [x] Crear componente para listado de conversaciones 
- [x] Crear componente para cargar detalles de conversación seleccionada
- [x] Agregar form para enviar mensajes y adjuntar archivos al chat
- [x] Si no se tiene un servicio de backend, usar data mock
- [x] Pruebas funcionales

**Comment by diloes** [comment]
¿ Qué tal vas @SebastianRamirezB ?

**Comment by SebastianRamirezB** [comment]
holaa, vamos bien, estaba haciendo unas consultas acerca del funcionamiento de los chats para un mejor desarrollo, hoy estaría desarrollando los componentes.

**Comment by diloes** [comment]
Ok Sebas !! Gracias
