### ISSUE TITLE
Desarrollar CRUD para editar información del usuario

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#79]
Como usuario, quiero tener disponible un endpoint desde el cual pueda editar mis datos usando la página de perfil de la app del cliente

- [x] Crear modelo y rutas para usuarios considerando relaciones con otras entidades
- [x]  Crear controlador y funciones CRUD para entidad de usuarios
- [x] Agregar opción para subir archivos (foto de perfil)
- [x]  Aplicar validaciones a modelo 
- [x]  Probar endpoints
- [x]  Documentar en swagger

**Comment by Ezequiel-Manfredi** [comment]
duda:
esta issue #79, no entiendo a que se refiere porque en la issue ya cerrada #28 ya fue parte de las tareas crear el crud de usuario.
