### ISSUE TITLE
Maquetar vista inicial de app admin

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/protectoras-animales#80]
Como usuario asociado a una protectora, quiero poder tener una app administrativa para poder registrarme, iniciar sesión y agregar datos relacionados a mi protectora y los centros que la componen

![image](https://user-images.githubusercontent.com/3885211/186204058-7ba0f3d8-02e1-4ea7-8c53-be0293d65460.png)

- [x] Maquetar vista inicial de login
- [x] Agregar validaciones al formulario
- [x] Agregar responsive design
- [x] Crear lógica y funciones para inicio de sesión 
- [x] Pruebas funcionales

**Comment by roqueheli** [comment]
@pedrovelasquez9 @diloes amigos, las pruebas funcionales deben ser automatizadas? Saludos

**Comment by diloes** [comment]
Seguro que @pedrovelasquez9 nos lo aclara. xD

**Comment by pedrovelasquez9** [comment]
@roqueheli @diloes no, con pruebas funcionales me refiero a probar lo desarrollado a nivel de interfaz, responsive y lógica funcional aplicada, básicamente que lo que hayan desarrollado funcione =)
